version: '2'
services:
    aditum-app:
        image: aditum
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aditum-mysql:3306/aditum?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aditum-mysql:
        extends:
            file: mysql.yml
            service: aditum-mysql
